name: 📝 Documentation Issue
description: Report a possible issue in the documentation
title: '📝 docs: <short description of the documentation issue>'
labels: 
  - "docs"
  - "require-triage"

body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting this issue! We'll try to triage it ASAP!
  
  - type: checkboxes
    attributes:
      label: Documentation Issue Checklist
      description: If any of these required steps are missed, we might not be able to review your issue.
      options:
        - label: I have read and agree to Express's [Code of Conduct](https://github.com/expressjs/.github/blob/master/CODE_OF_CONDUCT.md)
          required: true
        - label: I have searched for related issues but none matched my issue.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a description of the issue
    validations:
      required: true

  - type: textarea
    id: expectations
    attributes:
      label: Expectations
      description: Describe the expected behavior
    validations:
      required: true
