blank_issues_enabled: false
contact_links:
  - name: Security Report
    url: http://expressjs.com/en/resources/contributing.html#security-policies-and-procedures
    about: Email security reports to the maintainer list serve
